export const notifications = [
  {
    id: 38,
    title: 'ТЕСТ1',
    message: 'ТЕСТ',
    created: 1643697027,
    files: [],
    isReaded: false,
    isMeantToMe: true,
  },
  {
    id: 37,
    title: 'FUCK',
    message: 'FUCK',
    created: 1643696942,
    files: [],
    isReaded: false,
    isMeantToMe: true,
  },
  {
    id: 35,
    title: 'Тест',
    message: 'Тест',
    created: 1641793650,
    files: [
      {
        id: 30,
        name: 'Screenshot_20211102_150020.png',
        type: 'image/png',
        created: 1641793650,
        url: 'https://passport.amgpgu.ru/storage/4WOnlRkd2DJs30Rvjh0LvNJCJcfkTDnXb2z5WM7X.png',
      },
    ],
    isReaded: false,
    isMeantToMe: true,
  },
  {
    id: 34,
    title: 'Тест',
    message: 'Тест',
    created: 1641793474,
    files: [],
    isReaded: false,
    isMeantToMe: true,
  },
  {
    id: 33,
    title: 'Ехал грека',
    message: 'Ехал грека через реку',
    created: 1616047838,
    files: [
      {
        id: 12,
        name: 'oauth-login.vsdx',
        type: 'application/octet-stream',
        created: 1616047842,
        url: 'https://passport.amgpgu.ru/storage/8hIOGo1pOVX78ttRoq8X01KxMSAyxwLlua2dnFZJ.bin',
      },
      {
        id: 13,
        name: 'Жалоба в ГИС ЖКХ.docx',
        type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        created: 1616047843,
        url: 'https://passport.amgpgu.ru/storage/7ELSKEzm0RAz3Y1UAbzZa7dtYvdjwmAc4sGw5K8W.docx',
      },
    ],
    isReaded: true,
    isMeantToMe: true,
  },
  {
    id: 25,
    title: 'Тема',
    message: 'вввв',
    created: 1614569168,
    files: [],
    isReaded: false,
    isMeantToMe: true,
  },
  {
    id: 24,
    title: 'Тема #7',
    message: 'dadasdadada',
    created: 1613372528,
    files: [],
    isReaded: true,
    isMeantToMe: true,
  },
  {
    id: 23,
    title: 'Тема #6',
    message: 'dsdadasda',
    created: 1613372523,
    files: [],
    isReaded: true,
    isMeantToMe: true,
  },
  {
    id: 22,
    title: 'Тема #5',
    message: 'dsdsd sd',
    created: 1613372518,
    files: [],
    isReaded: true,
    isMeantToMe: true,
  },
  {
    id: 21,
    title: 'Тема #4',
    message: 'dsdsds',
    created: 1613372513,
    files: [],
    isReaded: true,
    isMeantToMe: true,
  },
  {
    id: 20,
    title: 'Тема#3',
    message: 'ddadada',
    created: 1613371571,
    files: [],
    isReaded: true,
    isMeantToMe: true,
  },
  {
    id: 19,
    title: 'Тема#2',
    message: 'daadada',
    created: 1613371567,
    files: [],
    isReaded: true,
    isMeantToMe: true,
  },
  {
    id: 18,
    title: 'Тема#1',
    message: 'edadada',
    created: 1613371563,
    files: [],
    isReaded: true,
    isMeantToMe: true,
  },
];

export const emptyNotifications = [];
